### ISSUE TITLE
This gem is outdated, I can take over the maintenance 

### ISSUE THREAD

**Issue by stefano-sarioli** [heelhook/intro.js-rails#18]
Hi, it looks like this gem is heavily outdated. 

If you want I can take over the gem for the maintenance, I was needing this gem for a project and forked it, but I think that it's better if the official gem referred by the Introjs documentation and present on the gem repository it's kept updated.

Let me know if I can help and thank you for doing the work of creating this gem in the first place 🙏 .

**Comment by Nittarab** [comment]
Hi, since intro.js becomes a payment library there is no sense to keep using this gem. 
Also in the current Rails version, you will no more use gem to add JS plugin...
